// Biblioteca de exercícios. eq: maq (máquina) | cabo (polia) | livre (halteres/barra) | peso (peso corporal)
const L = (id, name, eq, pri, sec, kind, sets, reps, rest, inc, effect, cues, alias = [], extra = {}) => ({ id, name, eq, pri, sec, kind, sets, reps, rest, inc, effect, cues, alias, ...extra });
export const LIB = [
  // PEITO
  L("sup_inc", "Supino inclinado na máquina", "maq", ["chest"], ["delt_f", "triceps"], "comp", 4, [6, 10], 120, 5, "Preenche a parte alta do peito.", ["Ajuste o banco para as pegadas ficarem na altura do peito alto.", "Escápulas coladas no encosto e empurre sem tirar as costas."], ["supino inclinado maquina"]),
  L("sup_reto", "Supino reto na máquina (chest press)", "maq", ["chest"], ["triceps", "delt_f"], "comp", 3, [6, 10], 120, 5, "Massa geral do peito.", ["Pegadas na altura do meio do peito, cotovelos a 45 graus.", "Suba sem esticar o cotovelo por completo."], ["chest press", "supino maquina"]),
  L("sup_maq", "Supino na máquina convergente (pegada neutra)", "maq", ["chest"], ["delt_f", "triceps"], "comp", 3, [10, 12], 90, 5, "Volume extra em ângulo e pegada diferentes.", ["Pegada neutra, cotovelos próximos ao tronco.", "Junte as mãos à frente e volte controlando."], ["convergente"]),
  L("sup_inc_h", "Supino inclinado com halteres", "livre", ["chest"], ["delt_f", "triceps"], "comp", 4, [6, 10], 120, 2, "Preenche a parte alta do peito.", ["Banco a 30 graus, escápulas juntas e para trás.", "Desça até alongar o peito e suba sem bater os halteres."]),
  L("sup_reto_h", "Supino reto com halteres", "livre", ["chest"], ["triceps", "delt_f"], "comp", 3, [6, 10], 120, 2, "Massa geral do peito com maior amplitude.", ["Cotovelos a 45 graus do tronco.", "Suba juntando os halteres sem bater."]),
  L("sup_reto_b", "Supino reto com barra", "livre", ["chest"], ["triceps", "delt_f"], "comp", 3, [6, 10], 150, 2.5, "Massa e força do peito.", ["Toque a barra na parte baixa do peito.", "Pés firmes no chão e escápulas travadas."], ["supino", "supino reto"]),
  L("sup_inc_b", "Supino inclinado com barra", "livre", ["chest"], ["delt_f", "triceps"], "comp", 3, [6, 10], 150, 2.5, "Peito alto e ombro frontal.", ["Banco a 30 graus, barra até a clavícula.", "Controle a descida."]),
  L("sup_inc_smith", "Supino inclinado no Smith (pouco usado)", "maq", ["chest"], ["delt_f", "triceps"], "comp", 4, [6, 10], 120, 5, "Peito alto com a barra guiada.", ["Banco a 30 graus, barra descendo até a clavícula.", "Escápulas juntas; destrave a barra girando o punho."], ["supino inclinado smith", "inclinado smith"]),
  L("sup_reto_smith", "Supino reto no Smith (pouco usado)", "maq", ["chest"], ["triceps", "delt_f"], "comp", 3, [8, 10], 120, 5, "Massa de peito com a barra guiada.", ["Barra desce até a parte baixa do peito.", "Pés firmes no chão e travas de segurança armadas."], ["supino smith", "supino reto smith"]),
  L("cross_ba", "Crossover baixo para alto", "cabo", ["chest"], ["delt_f"], "iso", 3, [12, 15], 75, 2.5, "Separação e definição do peito.", ["Polia baixa, braços quase esticados subindo até a linha do queixo.", "Aperte o peito no topo por 1 segundo."], ["crossover"]),
  L("cross_alto", "Crossover alto para baixo", "cabo", ["chest"], ["delt_f"], "iso", 3, [12, 15], 75, 2.5, "Parte inferior e interna do peito.", ["Polia alta, junte as mãos na altura do umbigo.", "Leve o peito à frente e mantenha os cotovelos levemente dobrados."]),
  L("peck", "Voador (peck deck)", "maq", ["chest"], ["delt_f"], "iso", 3, [12, 15], 75, 2.5, "Ativa o peito antes dos supinos e define o centro.", ["Cotovelos na altura do peito, junte à frente e aperte 1 segundo.", "Volte devagar até alongar, sem deixar a pilha descansar.", "Abra o treino de peito com ele: sinta o músculo antes dos supinos e use 5 a 10% menos carga neles."], ["voador", "crucifixo maquina"]),
  L("crucifixo", "Crucifixo com halteres", "livre", ["chest"], ["delt_f"], "iso", 3, [10, 12], 75, 2, "Alongamento e largura do peito.", ["Cotovelos levemente dobrados, abra até sentir o alongamento.", "Feche em arco como se abraçasse uma árvore."]),
  L("flexao", "Flexão de braço", "peso", ["chest"], ["triceps", "delt_f", "abs"], "comp", 3, [10, 20], 75, 0, "Peito e core com o peso do corpo.", ["Corpo em linha reta, cotovelos a 45 graus.", "Desça até o peito quase tocar o chão."], [], { bw: true }),
  L("mergulho", "Mergulho nas paralelas", "peso", ["chest", "triceps"], ["delt_f"], "comp", 3, [8, 12], 90, 0, "Peito inferior e tríceps.", ["Incline o tronco à frente para focar o peito.", "Desça até 90 graus de cotovelo."], ["paralelas", "dips"], { bw: true }),
  // COSTAS
  L("puxada", "Puxada frontal na máquina", "maq", ["lats"], ["biceps", "midback"], "comp", 4, [8, 10], 120, 5, "PRINCIPAL do V: alarga as costas.", ["Puxe os cotovelos para baixo e para o bolso, peito para frente.", "Suba devagar até alongar o dorsal, sem balançar."], ["puxada frontal", "pulldown", "puxador", "puxada alta"]),
  L("pux_sup", "Puxada supinada ou triângulo na polia", "cabo", ["lats"], ["biceps"], "comp", 3, [10, 12], 90, 5, "Fecha a parte de baixo do V.", ["Puxe até o peito alto, cotovelos rentes ao corpo.", "Controle a volta."], ["puxada supinada", "puxada triangulo"]),
  L("barra_fixa", "Barra fixa", "peso", ["lats"], ["biceps", "midback"], "comp", 3, [6, 10], 120, 0, "Largura das costas com o peso do corpo.", ["Comece de braços esticados e puxe o peito à barra.", "Evite balançar as pernas."], ["barra"], { bw: true }),
  L("remada", "Remada sentada na máquina", "maq", ["midback", "lats"], ["biceps", "delt_r", "traps"], "comp", 4, [8, 10], 120, 5, "Espessura das costas e postura.", ["Peito apoiado, puxe levando os cotovelos para trás.", "Junte as escápulas no fim e segure 1 segundo."], ["remada maquina", "remada sentada"]),
  L("rem_uni", "Remada unilateral na máquina", "maq", ["lats", "midback"], ["biceps"], "comp", 3, [10, 12], 90, 5, "Corrige assimetria e alonga o dorsal.", ["Um braço de cada vez, sem girar o tronco.", "Leve o cotovelo ao quadril e alongue bem na volta."], ["remada unilateral"]),
  L("rem_maq", "Remada baixa na polia (triângulo)", "cabo", ["midback"], ["lats", "delt_r", "biceps"], "comp", 3, [10, 12], 90, 5, "Espessura das costas.", ["Tronco firme, puxe o triângulo ao umbigo.", "Segure 1 segundo com as escápulas juntas."], ["remada baixa", "remada polia"]),
  L("rem_curv", "Remada curvada com barra", "livre", ["midback", "lats"], ["biceps", "delt_r", "lowback"], "comp", 3, [6, 10], 120, 2.5, "Espessura e força das costas.", ["Tronco a 45 graus, coluna neutra.", "Puxe a barra ao umbigo."], ["remada curvada", "remada barra"]),
  L("rem_cav", "Remada cavalinho", "livre", ["midback", "lats"], ["biceps", "delt_r"], "comp", 3, [8, 10], 120, 5, "Espessura das costas.", ["Peito para frente, puxe até o peito.", "Aperte as escápulas no final."], ["cavalinho", "t-bar"]),
  L("serrote", "Serrote (remada unilateral com halter)", "livre", ["lats", "midback"], ["biceps"], "comp", 3, [10, 12], 90, 2, "Dorsal e assimetrias.", ["Apoie a mão no banco, coluna neutra.", "Leve o cotovelo ao quadril."], ["serrote", "remada unilateral halter"]),
  L("pullover", "Pullover na polia", "cabo", ["lats"], ["chest", "triceps"], "iso", 3, [12, 15], 75, 2.5, "Alarga a caixa torácica visualmente.", ["Braços quase esticados, desça a barra até as coxas.", "Sinta o dorsal, não o tríceps."]),
  L("encolh", "Encolhimento com halteres", "livre", ["traps"], [], "iso", 3, [10, 15], 60, 2, "Trapézio superior.", ["Suba os ombros em direção às orelhas.", "Segure 1 segundo no topo."], ["encolhimento"]),
  // OMBROS
  L("desenv", "Desenvolvimento na máquina", "maq", ["delt_f", "delt_l"], ["triceps"], "comp", 3, [8, 10], 120, 5, "Massa de ombro.", ["Ajuste o banco para as pegadas ficarem na altura do queixo.", "Não trave os cotovelos em cima."], ["desenvolvimento maquina", "ombro maquina"]),
  L("desenv_h", "Desenvolvimento com halteres", "livre", ["delt_f", "delt_l"], ["triceps"], "comp", 3, [8, 10], 120, 2, "Massa de ombro.", ["Costas apoiadas, halteres sobem em leve arco.", "Não trave os cotovelos em cima."], ["desenvolvimento", "desenvolvimento halteres"]),
  L("elev_lat", "Elevação lateral na máquina", "maq", ["delt_l"], ["traps"], "iso", 4, [12, 15], 60, 2.5, "PRINCIPAL para ombro largo.", ["Cotovelos alinhados ao eixo da máquina, suba até a altura do ombro.", "Não encolha o trapézio."], ["elevacao lateral maquina"]),
  L("elev_cabo", "Elevação lateral no cabo", "cabo", ["delt_l"], [], "iso", 4, [12, 15], 60, 1.25, "Ombro largo com tensão constante.", ["Tensão constante do cabo, suba até a altura do ombro.", "Desça devagar."], ["elevacao lateral cabo"]),
  L("elev_lat_h", "Elevação lateral com halteres", "livre", ["delt_l"], ["traps"], "iso", 4, [12, 15], 60, 1, "Ombro largo.", ["Cotovelo levemente flexionado, suba até a altura do ombro.", "Pense em levar o cotovelo, não a mão."], ["elevacao lateral"]),
  L("face_pull", "Face pull na polia", "cabo", ["delt_r"], ["traps", "midback"], "iso", 3, [15, 15], 60, 2.5, "Ombro 3D visto de costas e ombro saudável.", ["Puxe a corda em direção ao rosto abrindo os cotovelos.", "Gire os punhos para fora no final."], ["face pull"]),
  L("cruc_inv", "Peck deck invertido", "maq", ["delt_r"], ["midback", "traps"], "iso", 3, [15, 15], 60, 2.5, "Ombro redondo visto de costas.", ["De frente para o encosto, abra os braços para trás.", "Cotovelos levemente flexionados, sem encolher o trapézio."], ["crucifixo inverso", "posterior de ombro"]),
  L("cruc_inv_h", "Crucifixo inverso com halteres", "livre", ["delt_r"], ["midback", "traps"], "iso", 3, [15, 15], 60, 1, "Ombro posterior.", ["Tronco inclinado, abra os braços para os lados.", "Cotovelos levemente flexionados."]),
  // BÍCEPS
  L("rosca_d", "Rosca na polia (barra reta)", "cabo", ["biceps"], ["forearms"], "iso", 3, [8, 10], 75, 2.5, "Volume do braço.", ["Cotovelos parados ao lado do corpo.", "Sem balançar o tronco."], ["rosca polia"]),
  L("rosca_m", "Rosca martelo na polia (corda)", "cabo", ["biceps", "forearms"], [], "iso", 3, [10, 12], 75, 2.5, "Espessura e altura do bíceps.", ["Pegada neutra, polegar para cima.", "Suba sem inclinar o tronco."]),
  L("rosca_inc", "Rosca alternada no cabo baixo", "cabo", ["biceps"], [], "iso", 3, [10, 12], 75, 2.5, "Pico e comprimento do bíceps.", ["Um braço de cada vez, braço levemente atrás do corpo.", "Alongue bem embaixo."]),
  L("rosca_sc", "Rosca Scott na máquina", "maq", ["biceps"], [], "iso", 3, [10, 12], 75, 5, "Espessura do bíceps.", ["Braços apoiados no banco, sem tirar o cotovelo.", "Não estique totalmente no fim para proteger o cotovelo."], ["rosca scott", "scott"]),
  L("rosca_h", "Rosca direta com barra", "livre", ["biceps"], ["forearms"], "iso", 3, [8, 10], 75, 2.5, "Volume do braço.", ["Cotovelos parados ao lado do corpo.", "Sem balançar o tronco."], ["rosca direta", "rosca"]),
  L("rosca_alt_h", "Rosca alternada com halteres", "livre", ["biceps"], [], "iso", 3, [10, 12], 75, 2, "Bíceps completo.", ["Gire o punho durante a subida.", "Desça devagar."], ["rosca alternada"]),
  L("rosca_mh", "Rosca martelo com halteres", "livre", ["biceps", "forearms"], [], "iso", 3, [10, 12], 75, 2, "Espessura do braço.", ["Pegada neutra, polegar para cima.", "Suba sem inclinar o tronco."], ["rosca martelo"]),
  // TRÍCEPS
  L("tri_corda", "Tríceps corda na polia", "cabo", ["triceps"], [], "iso", 3, [10, 12], 75, 2.5, "Braço mais largo visto de frente.", ["Cotovelos colados ao corpo.", "Abra a corda no fim do movimento."], ["triceps corda", "triceps polia", "triceps pulley"]),
  L("tri_testa", "Tríceps na máquina (extensão)", "maq", ["triceps"], [], "iso", 3, [8, 10], 90, 5, "Volume do braço visto de lado.", ["Ajuste o banco para o cotovelo ficar alinhado ao eixo da máquina.", "Estenda por completo e volte devagar."], ["triceps maquina"]),
  L("tri_barra", "Tríceps na polia (barra reta)", "cabo", ["triceps"], [], "iso", 3, [10, 12], 75, 2.5, "Volume do tríceps com carga alta.", ["Cotovelos colados ao corpo, só o antebraço se move.", "Estenda por completo e segure 1 segundo."], ["triceps barra", "triceps pulley", "pulley"]),
  L("tri_fr", "Tríceps francês na corda", "cabo", ["triceps"], [], "iso", 3, [10, 12], 75, 2.5, "Maior volume do braço.", ["Cotovelos apontando para frente, junto à cabeça.", "Estenda por completo."], ["triceps frances", "triceps testa corda"]),
  L("tri_testa_b", "Tríceps testa com barra W", "livre", ["triceps"], [], "iso", 3, [8, 10], 90, 2.5, "Volume do braço.", ["Cotovelos apontando para o teto.", "Desça controlando até perto da testa."], ["triceps testa"]),
  L("tri_banco", "Mergulho no banco", "peso", ["triceps"], ["chest", "delt_f"], "iso", 3, [10, 15], 75, 0, "Tríceps com o peso do corpo.", ["Cotovelos para trás, desça até 90 graus.", "Não deixe os ombros subirem."], [], { bw: true }),
  // PERNAS
  L("agacho", "Agachamento no Smith", "maq", ["quads", "glutes"], ["hams", "lowback", "abs"], "comp", 4, [6, 10], 150, 5, "Base do físico e grande estímulo metabólico.", ["Pés um pouco à frente da barra, coluna neutra.", "Desça até a coxa ficar paralela ou mais."], ["agachamento smith", "hack", "agachamento hack", "smith", "agachamento maquina"]),
  L("agach_livre", "Agachamento livre", "livre", ["quads", "glutes"], ["hams", "lowback", "abs"], "comp", 4, [6, 10], 150, 2.5, "Base do físico.", ["Joelhos acompanham a direção dos pés, coluna neutra.", "Desça até a coxa ficar paralela ou mais."], ["agachamento", "agachamento livre"]),
  L("leg", "Leg press", "maq", ["quads"], ["glutes"], "comp", 3, [10, 12], 120, 10, "Volume de perna sem sobrecarregar a lombar.", ["Pés na largura dos ombros, lombar sempre apoiada.", "Não trave os joelhos no topo."], ["leg", "leg 45", "leg press 45"]),
  L("afundo", "Afundo com halteres", "livre", ["quads", "glutes"], ["hams"], "comp", 3, [8, 12], 90, 2, "Perna e glúteo unilateral.", ["Passo longo, tronco ereto.", "Joelho da frente alinhado ao pé."], ["avanço", "avanco", "passada"]),
  L("stiff", "Stiff no Smith", "maq", ["hams", "glutes"], ["lowback"], "comp", 3, [8, 10], 120, 5, "Perna proporcional por trás.", ["Joelhos levemente flexionados, quadril vai para trás.", "Barra desliza rente às pernas, sinta o posterior alongar."], ["stiff smith"]),
  L("stiff_h", "Stiff com halteres", "livre", ["hams", "glutes"], ["lowback"], "comp", 3, [8, 10], 120, 2, "Posterior de coxa e glúteo.", ["Joelhos levemente flexionados, quadril para trás.", "Halteres rentes às pernas."], ["stiff", "terra romeno"]),
  L("extensora", "Cadeira extensora", "maq", ["quads"], [], "iso", 3, [12, 15], 75, 5, "Definição da frente da coxa.", ["Estenda por completo e segure 1 segundo.", "Desça controlando."], ["extensora"]),
  L("flexora", "Mesa flexora", "maq", ["hams"], [], "iso", 3, [12, 12], 75, 5, "Equilibra a perna.", ["Quadril colado no banco.", "Suba forte e desça em 2 a 3 segundos."], ["flexora", "mesa flexora"]),
  L("flex_sent", "Cadeira flexora (sentada)", "maq", ["hams"], [], "iso", 3, [10, 12], 75, 5, "Posterior de coxa.", ["Ajuste o encosto e o apoio das pernas.", "Flexione forte e volte devagar."], ["flexora sentada"]),
  L("abdutora", "Cadeira abdutora", "maq", ["glutes"], [], "iso", 3, [12, 15], 60, 5, "Glúteo médio.", ["Tronco levemente inclinado à frente.", "Abra com controle e segure 1 segundo."], ["abdutora"]),
  L("hip_thrust", "Elevação pélvica", "livre", ["glutes"], ["hams"], "comp", 3, [8, 12], 90, 5, "Glúteo forte e definido.", ["Queixo no peito, suba o quadril até alinhar tronco e coxa.", "Contraia o glúteo no topo."], ["hip thrust", "ponte"]),
  L("panturr", "Panturrilha na máquina ou leg press", "maq", ["calves"], [], "iso", 4, [12, 15], 60, 5, "Proporção da perna.", ["Amplitude total: alongue embaixo e suba na ponta.", "Pausa de 1 segundo no topo."], ["panturrilha", "gemeos"]),
  // ABDÔMEN
  L("abd_polia", "Abdominal na polia", "cabo", ["abs"], ["obliques"], "iso", 4, [10, 12], 60, 2.5, "Espessura do abdômen para aparecer ao secar.", ["Arredonde a coluna aproximando costelas do quadril.", "O movimento é do abdômen, não dos braços."], ["abdominal polia", "crunch polia"]),
  L("abd_maq", "Abdominal na máquina", "maq", ["abs"], ["obliques"], "iso", 3, [12, 15], 60, 5, "Espessura do abdômen.", ["Flexione o tronco usando o abdômen.", "Solte devagar sem perder tensão."], ["abdominal maquina"]),
  L("elev_perna", "Elevação de pernas", "peso", ["abs"], ["obliques"], "iso", 3, [12, 15], 60, 0, "Parte baixa do abdômen.", ["Suba o quadril no final, sem balançar.", "Desça devagar sem perder a tensão."], ["abdominal infra", "elevacao de pernas"], { bw: true }),
  L("abd_supra", "Abdominal supra no chão", "peso", ["abs"], ["obliques"], "iso", 3, [15, 20], 45, 0, "Reto abdominal.", ["Suba só as escápulas, sem puxar o pescoço.", "Contraia o abdômen no topo."], ["abdominal", "abdominal supra", "crunch"], { bw: true }),
  L("prancha", "Prancha", "peso", ["abs"], ["obliques", "lowback"], "iso", 3, [40, 40], 45, 0, "Estabilidade do tronco.", ["Corpo em linha reta, glúteos contraídos.", "Não deixe o quadril cair."], ["prancha isometrica"], { kind2: "time" }),
];
LIB.forEach((e) => { if (e.id === "prancha") { e.kind = "time"; } });
export const LIB_BY_ID = Object.fromEntries(LIB.map((e) => [e.id, e]));
export const EQ_NAME = { maq: "Máquina", cabo: "Polia", livre: "Livre", peso: "Peso do corpo" };

// aparelho de cada exercício (ilustração) e o que nem toda academia tem
const MACH = { sup_inc: "incline_press", sup_reto: "chest_press", sup_maq: "chest_press", sup_inc_smith: "smith", sup_reto_smith: "smith", cross_ba: "cable_cross", cross_alto: "cable_cross", peck: "pec_deck", puxada: "pulldown", pux_sup: "pulldown", barra_fixa: "pullup", remada: "row_machine", rem_uni: "row_machine", rem_maq: "cable_row", pullover: "cable_tower", desenv: "shoulder_press", elev_lat: "shoulder_press", elev_cabo: "cable_tower", face_pull: "cable_tower", cruc_inv: "pec_deck", rosca_d: "cable_tower", rosca_m: "cable_tower", rosca_inc: "cable_tower", tri_corda: "cable_tower", tri_fr: "cable_tower", tri_barra: "cable_tower", agacho: "smith", leg: "leg_press", stiff: "smith", extensora: "leg_ext", flexora: "leg_curl", flex_sent: "leg_curl", abdutora: "abductor", panturr: "calf", abd_polia: "cable_crunch", abd_maq: "ab_machine", elev_perna: "captain", prancha: "floor", abd_supra: "floor", flexao: "floor" };
export const RARE_IDS = ["rem_uni", "elev_lat", "rosca_sc", "tri_testa", "rem_cav", "sup_inc_smith", "sup_reto_smith"];
const RARE_LABEL = { sup_inc_smith: "Pouco usado: prefira a máquina", sup_reto_smith: "Pouco usado: prefira a máquina" };
LIB.forEach((e) => { e.rir = e.kind === "time" ? null : e.kind === "comp" ? "2-3" : "2"; e.mach = MACH[e.id] || null; e.rare = RARE_IDS.includes(e.id); if (RARE_LABEL[e.id]) e.rareLabel = RARE_LABEL[e.id]; });
